services:

  lexi-api:
    hostname: lexi-api
    container_name: lexi-api
    image: lexi-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - lexi-api
    volumes:
      - ./nginx/ssl:/etc/ssl


volumes:
  redis_data:
    external: false