FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY ssl/cert.pem /etc/ssl/cert.pem
COPY ssl/key.pem /etc/ssl/key.pem
COPY ssl/docker.loc.crt /etc/ssl/docker.loc.crt
COPY ssl/docker.loc.key /etc/ssl/docker.loc.key